server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  datasource:
    car-rental:
      url: jdbc:postgresql://localhost:5432/car_rental
      username: postgres
      password: xkool
    driver-class-name: org.postgresql.Driver
  application:
    name: car-rental
  profiles:
    active: linux
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false
    # flyway database version controll
  flyway:
    clean-disabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
  sql:
    init:
      platform: postgres

encrypt:
  md5: testmd5encryptor
